---
- name: Install HTTPD Web Server for RPM
  yum: name=httpd state=latest
  when: ansible_os_family == "RedHat"

- name: Install Apache Web Server for Debian
  apt: name=apache2 state=latest
  when: ansible_os_family == "Debian"

- name: Print Linux Family
  debug: var=ansible_os_family
  
  
      
- name:     Generate index.html from jinja2 template and copy to the remote host
  template: src=index.j2 dest={{ dest_folder }}/index.html mode=0555
  notify:   Restart Httpd
  when:     ansible_os_family == "RedHat"
  
- name:     Generate index.html from jinja2 template and copy to the remote host
  template: src=index.j2 dest={{ dest_folder }}/index.html mode=0555
  notify:   Restart Apache2
  when:     ansible_os_family == "Debian"
  
- name: Start HTTPD Web Server
  service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: Start Apache Web Server
  service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"